### PR TITLE
 Fix real as int for incremental

### LINKED ISSUE #3956: solve-real-as-int fatal failure at src/theory/theory_model.cpp:374
Hi,
For this formula:
~~~~
(set-logic NRA)
(set-option :solve-real-as-int true)
(declare-const v0 Bool)
(declare-const v1 Bool)
(declare-const v2 Bool)
(declare-const v3 Bool)
(push 1)
(declare-const v4 Bool)
(declare-const r1 Real)
(pop 1)
(declare-const v5 Bool)
(declare-const r2 Real)
(declare-const r3 Real)
(push 1)
(declare-const r4 Real)
(declare-const v6 Bool)
(declare-const v7 Bool)
(pop 1)
(declare-const v8 Bool)
(declare-const v9 Bool)
(assert (forall ((q0 Bool) (q1 Bool) (q2 Real)) (=> (> r3 q2 q2 q2 r2) (distinct q1 q1 v8))))
(declare-const r5 Real)
(push 1)
(declare-const v10 Bool)
(assert (exists ((q3 Real) (q4 Real)) (distinct r2 (- 12.0) (- 12.0))))
(pop 1)
(push 1)
(declare-const v11 Bool)
(declare-const v12 Bool)
(push 1)
(declare-const r6 Real)
(declare-const r7 Real)
(pop 1)
(declare-const v13 Bool)
(assert (or (<= r3 (* (- 12.0) r2 12.0) 12.0) (distinct r2 (- 12.0) (- 12.0)) v8 (>= (* (- 12.0) r2 12.0) 12.0 (* (- 12.0) r2 12.0)) v3))
(assert (or v5 (distinct r2 r5 r3 (- 12.0) r3) v3))
(assert (or (distinct (* r2 (- 12.0)) r2 r2 (* (- 12.0) r2 12.0) (- 12.0))))
(assert (or (>= (* (- 12.0) r2 12.0) 12.0 (* (- 12.0) r2 12.0)) (< r3 (- 12.0) (- 12.0) r2)))
(assert (or v8))
(assert (or v0))
(assert (or v1 v2 v1 (not v9) v5 v5 v0))
(assert (or v0))
(check-sat)
~~~~
CVC4 incremenal mode throws out a fatal failure:
~~~~
Fatal failure within void CVC4::theory::TheoryModel::addSubstitution(CVC4::TNode, CVC4::TNode, bool) at /home/peisen/test/tofuzz/CVC4/src/theory/theory_model.cpp:374
Internal error detectedTwo incompatible substitutions added to TheoryModel:
the term:    r2
old mapping: __realToIntInternal_var_2
new mapping: __realToIntInternal_var_3
Aborted (core dumped)
~~~~
OS: Ubuntu 16.04
Commit: a0b35a8

### LINKED ISSUE #3969: check-unsat-cores + solve-real-as-int: fatal failure at theory_preprocess.cpp:39
Hi,
For this formula:
[thpreprocess39.txt](https://github.com/CVC4/CVC4/files/4306727/thpreprocess39.txt)

CVC4 incremental mode throws out a fatal failure:
~~~~
Fatal failure within virtual CVC4::preprocessing::PreprocessingPassResult CVC4::preprocessing::passes::TheoryPreprocess::applyInternal(CVC4::preprocessing::AssertionPipeline*) at /home/peisen/test/tofuzz/CVC4/src/preprocessing/passes/theory_preprocess.cpp:39
Check failure

 Rewriter::rewrite(a) == a
~~~~

OS: Ubuntu 16.04
Commit: a0b35a8

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #3956 and fixes #3969.

### CODE REVIEW

**Comment by ajreynol** [comment]
For the latter, --solve-real-as-int cannot return "unsat" so this is not possible.  I can add a sat test.

File: src/preprocessing/passes/real_to_int.cpp [hunk 1]
```diff
@@ -171,8 +171,11 @@ Node RealToInt::realToIntInternal(TNode n, NodeMap& cache, std::vector<Node>& va
                              nm->integerType(),
                              "Variable introduced in realToIntInternal pass");
           var_eq.push_back(n.eqNode(ret));
-          TheoryModel* m = d_preprocContext->getTheoryEngine()->getModel();
```
Comment (yoni206) [inline src/preprocessing/passes/real_to_int.cpp]: Since this line touched models, I suggest adding a `--produce-models` and `(get-model)` to the test. Is that possible?

**Comment by ajreynol** [comment]
We run --check-models by default, so this is implied.  (get-model) would only test the model printing code.
