### PR TITLE
Fix issues with printing parametric datatypes in smt2

### LINKED ISSUE #1852: Assertion failure when dumping datatypes regression
```
$ builds/bin/cvc4 --preprocess-only --lang=smt2.5 --dump raw-benchmark test/regress/regress0/bug541.smt2
(set-option :incremental false)
(set-logic ALL_SUPPORTED)
(declare-datatypes () ((__cvc4_tuple (__cvc4_tuple_ctor))
))
(declare-sort T1 0)
(declare-sort T2 0)
(declare-datatypes () ((Pair (mk-pair (first T1) (second T2)))
))
CVC4 was terminated by the C++ runtime.
Perhaps an exception was thrown during stack unwinding.  (Don't do that.)
terminate called after throwing an instance of 'CVC4::AssertionException'
  what():  Assertion failure
void CVC4::expr::NodeValue::dec()
../../../../src/expr/node_value.h:442:
  NodeManager::currentNM() != __null
No current NodeManager on destruction of NodeValue: maybe a public CVC4 interface function is missing a NodeManagerScope ?
Aborted (core dumped)
```

### LINKED ISSUE #1870: Illegal argument error when parsing dumped SMT2.5 DT benchmark
```
$ builds/bin/cvc4 --preprocess-only --lang=smt2.5 --dump raw-benchmark -qq test/regress/regress0/datatypes/dt-param-card4-bool-sat.smt2 > dt.smt2
$ builds/bin/cvc4 --lang=smt2.5 dt.smt2
(error "Parse Error: dt.smt2:10.35: Illegal argument detected
CVC4::Type CVC4::SymbolTable::Implementation::lookupType(const string&, const std::vector<CVC4::Type>&) const
  `params' is a bad argument; expected p.first.size() == params.size() to hold
type constructor arity is wrong: `Pair' requires 0 parameters but was provided 2")
```

### PR DESCRIPTION
**Pull request by ajreynol**
This includes:
- Property type casting arguments of parametric constructors,
- Not printing out spurious declare-sort for intermediate parametric sorts and unresolved type constructors,
- Printing parameters properly for both the 2.5 and 2.6 forms for datatypes.

This fixes #1852 and fixes #1870 (those benchmarks can now be dumped/re-parsed).

### CODE REVIEW

File: src/printer/smt2/smt2_printer.cpp [hunk 1]
```diff
@@ -1907,15 +1919,74 @@ static void toStream(std::ostream& out,
...
+      {
+        out << (j > 0 ? " " : "") << d.getParameter(j);
+      }
+    }
+    else
+    {
+      out << std::endl;
+      out << "ERROR: datatypes in each block must have identical parameter "
+             "lists.";
+      out << std::endl;
```
Comment (4tXJ7f) [inline src/printer/smt2/smt2_printer.cpp]: Instead of printing this to `out`, we should probably use `Error()` s.t. the error ends up on stderr instead of stdout (or in a file). We could also add an `AlwaysAssert(false)` to exit if this point is reached.

File: src/printer/smt2/smt2_printer.cpp [hunk 2]
```diff
@@ -1907,15 +1919,74 @@ static void toStream(std::ostream& out,
...
+        out << ")";
+      }
     }
     out << ")";
   }
   else
   {
-    out << " () (";
+    out << " (";
+    // can only print if all datatypes in this block have the same parameters
```
Comment (4tXJ7f) [inline src/printer/smt2/smt2_printer.cpp]: Nit: Missing period at the end of this line (makes the comment confusing to parse).

File: src/printer/smt2/smt2_printer.cpp [hunk 3]
```diff
@@ -1907,15 +1919,74 @@ static void toStream(std::ostream& out,
...
+    // different parameter lists.
+    bool success = true;
+    const Datatype& d = datatypes[0].getDatatype();
+    unsigned nparam = d.getNumParameters();
+    for (unsigned j = 1, ndt = datatypes.size(); j < ndt; j++)
+    {
+      const Datatype& dj = datatypes[j].getDatatype();
+      if (dj.getNumParameters() != nparam)
+      {
+        success = false;
```
Comment (4tXJ7f) [inline src/printer/smt2/smt2_printer.cpp]: Nit: Why not just break here and remove lines 1970-1973 (similar to the break statement on line 1966)?

Comment (ajreynol) [reply src/printer/smt2/smt2_printer.cpp]: Because lines 1970-1973 also handle the case where the else branch set success to false.

File: src/printer/smt2/smt2_printer.cpp (hunk 1 above)
Comment (ajreynol) [reply src/printer/smt2/smt2_printer.cpp]: I'm following the convention here: https://github.com/CVC4/CVC4/blob/master/src/printer/smt2/smt2_printer.cpp#L1251

Let me know if you think this should change.  (There are advantages I suppose to printing on out, since it ensures that the user is informed of what went wrong in their printing).

File: src/printer/smt2/smt2_printer.cpp (hunk 3 above)
Comment (4tXJ7f) [reply src/printer/smt2/smt2_printer.cpp]: But that one `break`s anyway :)

Comment (ajreynol) [reply src/printer/smt2/smt2_printer.cpp]: Right, so a break here is redundant :)

Comment (4tXJ7f) [reply src/printer/smt2/smt2_printer.cpp]: I don't know if it was the lack of caffeine or something else but I misread the code and missed the fact that the other `break` was for the inner loop.

File: src/printer/smt2/smt2_printer.cpp (hunk 1 above)
Comment (4tXJ7f) [reply src/printer/smt2/smt2_printer.cpp]: I still think that errors belong on stderr but it looks like this is out of scope for this PR.
