### PR TITLE
Consolidate options that disable produceModels

### LINKED ISSUE #3936: Fatal failure for QF_BV instance at smt_engine.cpp:4884
Hi,
For this formula,
[smtengine4884.txt](https://github.com/CVC4/CVC4/files/4301860/smtengine4884.txt)

---minimized test---
~~~~
(set-logic ALL)
(set-option :check-models true)
(set-option :incremental false)
(set-option :sort-inference true)
(declare-const v0 Bool)
(declare-const v1 Bool)
(declare-const v2 Bool)
(declare-const v3 Bool)
(declare-const v4 Bool)
(declare-const v5 Bool)
(declare-const v6 Bool)
(declare-const v7 Bool)
(declare-const v8 Bool)
(declare-const i1 Int)
(declare-const i2 Int)
(declare-const i4 Int)
(declare-const i10 Int)
(declare-const r0 Real)
(declare-const r1 Real)
(declare-const r2 Real)
(declare-const r3 Real)
(declare-const r4 Real)
(declare-const r5 Real)
(declare-const r6 Real)
(assert v6)
(check-sat)
(exit)
~~~~

Run command
~~~~
cvc4  --tlimit-per=100 name
~~~~

cvc4-nightly (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-03-07-x86_64-linux-opt) 
crashed with the information:
~~~~
Fatal failure within void CVC4::SmtEngine::checkModel(bool) at /barrett/scratch/cvc4-nightly/src/cvc4-2020-03-07/src/smt/smt_engine.cpp:4884
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     v1
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
~~~~

OS: Ubuntu 16.04

### PR DESCRIPTION
**Pull request by ajreynol**
Also adds --sort-inference to this list, fixes #3936.

### CODE REVIEW

File: src/smt/smt_engine.cpp [hunk 1]
```diff
@@ -2401,6 +2324,77 @@ void SmtEngine::setDefaults() {
...
+               << sOptNoModel.str() << endl;
+      setOption("produce-models", SExpr("false"));
+    }
+    if (options::produceAssignments())
+    {
+      if (options::produceAssignments.wasSetByUser())
+      {
+        std::stringstream ss;
+        ss << "Cannot use " << sOptNoModel.str()
+           << " model generation (produce-assignments).";
```
Comment (mpreiner) [inline src/smt/smt_engine.cpp]:
```suggestion
           << " with model generation (produce-assignments).";
```

File: src/smt/smt_engine.cpp [hunk 2]
```diff
@@ -2401,6 +2324,77 @@ void SmtEngine::setDefaults() {
...
+               << sOptNoModel.str() << endl;
+      setOption("produce-assignments", SExpr("false"));
+    }
+    if (options::checkModels())
+    {
+      if (options::checkModels.wasSetByUser())
+      {
+        std::stringstream ss;
+        ss << "Cannot use " << sOptNoModel.str()
+           << " model generation (check-models).";
```
Comment (mpreiner) [inline src/smt/smt_engine.cpp]:
```suggestion
           << " with model generation (check-models).";
```

File: src/smt/smt_engine.cpp [hunk 3]
```diff
@@ -2401,6 +2324,77 @@ void SmtEngine::setDefaults() {
                  << endl;
     options::stringProcessLoopMode.set(options::ProcessLoopMode::SIMPLE);
   }
+
+  // !!! All options that require disabling models go here
+  bool disableModels = false;
+  std::stringstream sOptNoModel;
```
Comment (mpreiner) [inline src/smt/smt_engine.cpp]: `std::string` would be sufficient here.
