### PR TITLE
Fix global-declarations support

### LINKED ISSUE #3402: bug with global-declarations and declare-datatypes
The following script demonstrates that CVC4 forgets datatype declarations after a pop even when the `global-declarations` option is set.

```
$ cat cvc4bug.smt2
(set-option :global-declarations true)
(set-logic ALL_SUPPORTED)

(push 1)
(declare-datatype Struct1 (par (T0) ((mk-struct1 (struct1-proj0 T0)))))
(declare-fun x () (Struct1 Bool))
(pop 1)

;(assert (= x false))

(define-fun y () (Struct1 Bool) (mk-struct1 true))

$ cvc4 -i cvc4bug.smt2
(error "Parse Error: cvc4bug.smt2:11.31: Symbol 'Struct1' not declared as a type

  (define-fun y () (Struct1 Bool) (mk-struct1 true))
                    ^
")

$ cvc4 --version
This is CVC4 version 1.7-prerelease [git master 1955e4b5]
```

I'm using homebrew CVC4 for OS X, which is pinned to a prerelease for some reason... I've had trouble compiling CVC4 from source in the past.

Note that the constant `x` remains in scope, even though it's type becomes inaccessable.  Morever, CVC4 remembers its type: if you uncomment the assertion above, you get the following error:
```
(error "Subexpressions must have a common base type:
Equation: (= x false)
Type 1: (Struct1 Bool)
Type 2: Bool
")
```

### PR DESCRIPTION
**Pull request by 4tXJ7f**
Fixes #3402. Previously, we were removing datatype and uninterpreted
sort declarations when popping the user context even with
`global-declarations` set to true. However, the SMT-LIB standard says
that ":global-declarations [...] makes all definitions and declarations
global and not removable by pop operations". This commit fixes those
issues by making sure that the uninterpreted sorts as well as the
datatype sorts, constructors, and testers are inserted at level zero if
global declarations are enabled.

### CODE REVIEW

File: src/parser/parser.h [hunk 1]
```diff
@@ -527,11 +527,15 @@ class CVC4_PUBLIC Parser {
                  bool levelZero = false, bool doOverload = false);
 
   /** Create a new type definition. */
```
Comment (ajreynol) [inline src/parser/parser.h]: Can you add documentation for the arguments (especially the added one).

Comment (4tXJ7f) [reply src/parser/parser.h]: Good point, done.

File: src/parser/parser.h [hunk 2]
```diff
@@ -527,11 +527,15 @@ class CVC4_PUBLIC Parser {
...
-  void defineType(const std::string& name, const Type& type);
+  void defineType(const std::string& name,
+                  const Type& type,
+                  bool levelZero = false);
 
   /** Create a new (parameterized) type definition. */
   void defineType(const std::string& name,
-                  const std::vector<Type>& params, const Type& type);
+                  const std::vector<Type>& params,
```
[the remark this answers is not in the document]
Comment (4tXJ7f) [reply src/parser/parser.h]: Good point, done.
