### PR TITLE
 Fix string ext inference for rewrites that introduce negation

### LINKED ISSUE #2616: Strings input does not terminate when reaching timeout
When running the following input, it does not terminate after 3 seconds when using the options `--strings-fmf --strings-exp --tlimit 3000`:

```
(set-logic SLIA)
(declare-const x String)
(declare-const y String)
(assert (not (= (str.replace "A" (str.replace x "A" y) x) (str.replace "A" x (str.replace x y x)))))
(check-sat)
```

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #2616.

### CODE REVIEW

File: src/theory/strings/theory_strings.cpp [hunk 1]
```diff
@@ -1778,18 +1778,21 @@ void TheoryStrings::checkExtfInference( Node n, Node nr, ExtfInfoTmp& in, int ef
...
           conc = Rewriter::rewrite(conc);
+          conc = conc.negate();
           bool do_infer = false;
+          bool pol = conc.getKind() != NOT;
+          Node lit = pol ? conc : conc[0];
           if (conc.getKind() == EQUAL)
           {
-            do_infer = !areDisequal(conc[0], conc[1]);
+            do_infer = pol ? !areEqual(conc[0], conc[1])
+                           : !areDisequal(conc[0], conc[1]);
```
Comment (4tXJ7f) [inline src/theory/strings/theory_strings.cpp]: Shouldn't this be `lit[0]` and `lit[1]` instead of `conc[0]` and `conc[1]`?

File: src/theory/strings/theory_strings.cpp [hunk 2]
```diff
@@ -1778,18 +1778,21 @@ void TheoryStrings::checkExtfInference( Node n, Node nr, ExtfInfoTmp& in, int ef
           Node conc =
               nm->mkNode(STRING_STRCTN, pol ? nr[1] : onr, pol ? onr : nr[1]);
           conc = Rewriter::rewrite(conc);
+          conc = conc.negate();
           bool do_infer = false;
+          bool pol = conc.getKind() != NOT;
+          Node lit = pol ? conc : conc[0];
           if (conc.getKind() == EQUAL)
```
Comment (4tXJ7f) [inline src/theory/strings/theory_strings.cpp]: Shouldn't this be `lit.getKind()`?

File: src/theory/strings/theory_strings.cpp [hunk 3]
```diff
@@ -1778,18 +1778,21 @@ void TheoryStrings::checkExtfInference( Node n, Node nr, ExtfInfoTmp& in, int ef
...
           {
-            do_infer = !areDisequal(conc[0], conc[1]);
+            do_infer = pol ? !areEqual(conc[0], conc[1])
+                           : !areDisequal(conc[0], conc[1]);
           }
           else
           {
-            do_infer = !areEqual(conc, d_false);
+            do_infer = !areEqual(conc, pol ? d_true : d_false);
```
Comment (4tXJ7f) [inline src/theory/strings/theory_strings.cpp]: Shouldn't that be `pol ? d_false : d_true`? `conc` should be not equal to `d_false` if it is positive.
