### PR TITLE
Fix issues with real to int

### LINKED ISSUE #3913: QF_BV instance segment fault (NPD)
Hi,
For this formula,

[cvcnpd.txt](https://github.com/CVC4/CVC4/files/4285747/cvcnpd.txt)

cvc4-nightly (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-03-03-x86_64-linux-opt) incremental mode
crashed

~~~~
CVC4 suffered a segfault.
Offending address is 0x29
Looks like a NULL pointer was dereferenced.
~~~~

OS: Ubuntu 16.04

### LINKED ISSUE #3915: Fatal failure for UFNIA instance at src/smt/smt_engine.cpp:4808
Hi,
For this formula,
[checkmodel1.txt](https://github.com/CVC4/CVC4/files/4286447/checkmodel1.txt)

--minimized test case--
[checkmodel1-minimized.txt](https://github.com/CVC4/CVC4/files/4288106/checkmodel1-minimized.txt)

cvc4-nightly (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-03-03-x86_64-linux-opt) incremental mode
crashed with the information:

~~~~
Fatal failure within void CVC4::SmtEngine::checkModel(bool) at /barrett/scratch/cvc4-nightly/src/cvc4-2020-03-03/src/smt/smt_engine.cpp:4808 
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL: model value for __realToIntInternal_var_5 is false
value type is Bool
should be of type Int
~~~~

OS: Ubuntu 16.04

### LINKED ISSUE #3916: Fatal failure for "ALL" instance at src/theory/theory_engine.cpp:682
Hi,
For this formula,

[theneine682_1.txt](https://github.com/CVC4/CVC4/files/4286744/theneine682_1.txt)

cvc4-nightly (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-03-03-x86_64-linux-opt) incremental mode
crashed with the information:

~~~~
Fatal failure within void CVC4::TheoryEngine::check(CVC4::theory::Theory::Effort) at /barrett/scratch/cvc4-nightly/src/cvc4-2020-03-03/src/theory/theory_engine.cpp:682
Check failure
     d_curr_model->isBuiltSuccess()
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04

### PR DESCRIPTION
**Pull request by ajreynol**
This fixes a few issues in the real to int preprocessing pass. Previously it was not robust to cases where the input had constraints that were not over the reals.

Fixes #3915 and fixes #3913 and fixes #3916.

### CODE REVIEW

File: src/preprocessing/passes/real_to_int.cpp [hunk 1]
```diff
@@ -137,11 +136,6 @@ Node RealToInt::realToIntInternal(TNode n, NodeMap& cache, std::vector<Node>& va
             Trace("real-as-int") << "   " << n << std::endl;
             Trace("real-as-int") << "   " << ret << std::endl;
           }
```
Comment (yoni206) [inline src/preprocessing/passes/real_to_int.cpp]: What happens if you have an array from real to real, and then you have a selection term with a real. Do you change the selection variable to Int? Shouldn't you then convert the array to be from Int to Int? Similarly to UF and other "containers".

Comment (ajreynol) [reply src/preprocessing/passes/real_to_int.cpp]: Int is a subtype of Real in CVC4, so changing Real -> Int is always safe.  No change should be necessary.
