### PR TITLE
Fix issue 5271

### LINKED ISSUE #5271: (sets-ext) Invalid model on set constraint
Hi, for this formula, CVC4 ae8e63d4be throws a fatal failure
~~~~
(declare-const v0 Bool)
(declare-const v3 Bool)
(declare-const v7 Bool)
(declare-const i3 Int)
(declare-const i6 Int)
(declare-fun st2 () (Set Int))
(declare-fun st3 () (Set Int))
(declare-fun st5 () (Set Int))
(declare-fun st7 () (Set Int))
(declare-fun st11 () (Set Int))
(declare-fun st13 () (Set Int))
(declare-const i21 Int)
(declare-const i23 Int)
(declare-const i25 Int)
(declare-const v12 Bool)
(assert (> (card st3) (ite (=> v7 v3) 46 1960)))
(declare-const v14 Bool)
(declare-const v19 Bool)
(declare-const v22 Bool)
(declare-const v27 Bool)
(assert (and (or v19 (= i21 i3) (not v0)) (or v22 (>= 53 i23 76) v12) (or (member (mod i6 46) st7) v27 (subset (union st5 (intersection st11 st2)) st5)) (or (member i25 st13) v22 (>= 53 i23 76)) (or (subset (union st5 (intersection st11 st2)) st5) v14 v12) (or v27 (subset (union st5 (intersection st11 st2)) st5) v22) (or v12 v12 (>= 53 i23 76))))
(check-sat)
~~~~
~~~~
./cvc4 --check-models --sets-ext -q xx.smt2
Fatal failure within void CVC4::SmtEngine::checkModel(bool) at /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:1755
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (> (card st3) (ite (=> v7 v3) 46 1960))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted
~~~~

### PR DESCRIPTION
**Pull request by mudathirmahgoub**
This PR fixes #5271 by splitting on the equality of set members which ensures members are distinct when collectModelInfo is called.
Co-authored-by: Andrew Reynolds andrew-reynolds@uiowa.edu

### CODE REVIEW

File: src/theory/sets/theory_sets_private.cpp [hunk 1]
```diff
@@ -850,7 +850,7 @@ void TheorySetsPrivate::addCarePairs(TNodeTrie* t1,
     {
       Node f1 = t1->getData();
       Node f2 = t2->getData();
-      if (!d_state.areEqual(f1, f2))
+      if (f1.getKind() == MEMBER || !d_state.areEqual(f1, f2))
```
Comment (ajreynol) [inline src/theory/sets/theory_sets_private.cpp:853]: Can you add some comments about what we discussed?  That member should not be treated like a function symbol when building the care graph. Maybe give a very basic example we discussed.

**Review by ajreynol — CHANGES_REQUESTED** [review]

File: src/theory/sets/theory_sets_private.cpp (hunk 1 above)
Comment (mudathirmahgoub) [reply src/theory/sets/theory_sets_private.cpp:863]: Done.

**Review by ajreynol — APPROVED** [review]
