### PR TITLE
Fix node arity issue in reduction of int2bv

### LINKED ISSUE #3776: fatal failure at CVC4/src/./expr/node_builder.h:961
Hi,
For this formula:
```
(declare-fun t () Int)
(assert (= t (bv2nat ((_ int2bv 1) t))))
(check-sat)
```
CVC4  throws out a fatal failure:
```
Fatal failure within CVC4::expr::NodeValue* CVC4::NodeBuilder<N>::constructNV() [with unsigned int nchild_thresh = 10] at CVC4/src/./expr/node_builder.h:961
Check failure
 getNumChildren() >= kind::metakind::getLowerBoundForKind(getKind())
Nodes with kind BITVECTOR_CONCAT must have at least 2 children (the one under construction has 1)

```

OS: Ubuntu 18.04
Commit: 8fe0467

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #3776.

### CODE REVIEW

File: src/theory/bv/theory_bv_utils.cpp [hunk 1]
```diff
@@ -481,6 +481,33 @@ Node eliminateBv2Nat(TNode node)
   return children.size() == 1 ? children[0] : nm->mkNode(kind::PLUS, children);
 }
 
+Node eliminateInt2Bv(TNode node)
+{
+  const unsigned size = node.getOperator().getConst<IntToBitVector>().size;
```
Comment (mpreiner) [inline src/theory/bv/theory_bv_utils.cpp]:
```suggestion
  const uint32_t size = node.getOperator().getConst<IntToBitVector>().size;
```

File: src/theory/bv/theory_bv_utils.h [hunk 2]
```diff
@@ -215,6 +215,15 @@ void intersect(const std::vector<uint32_t>& v1,
  * where n is the bitwidth of x.
  */
 Node eliminateBv2Nat(TNode node);
+/**
+ * Returns the rewritten form of node, which is a term of the form int2bv(x).
+ * The return value of this method is the concatenation term:
+ *   (bvconcat ite( (>= (mod x (^ 2 n)) (^ 2 (n-1))) (_ bv1 1) (_ bv1 0))
+ *             ...
+ *             ite( (>= (mod x (^ 2 1)) (^ 2 0)) (_ bv1 1) (_ bv1 0)))
+ * where n is the bitwidth of x.
```
Comment (mpreiner) [inline src/theory/bv/theory_bv_utils.h]:
```suggestion
 * where n is the bit-width of x.
```
