### PR TITLE
Fixes memory leak when an exception goes through runCvc4(). (Fixes #4590)

### LINKED ISSUE #4590: Memory leak on QF_NIA formula (ackermann)
Hi, for the following formula
~~~~
(set-logic QF_NIA)
(set-option :ackermann true)
(assert (! true :named IP_1))
(exit)
~~~~

when executing `cvc4 --incremental fname.smt2`, cvc 61734b41b throws a leak
~~~~
CVC4 Error:
Error in option parsing: Incremental Ackermannization is currently not supported.

Please use --help to get help on command-line options.

==126462==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7f0690eb9592 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99592)
    #1 0x7f068fb147f7 in attribute /home/peisen/test/tofuzz/CVC4/build/src/parser/smt2/Smt2Parser.c:13073
    #2 0x7f068faf87fb in termNonVariable /home/peisen/test/tofuzz/CVC4/build/src/parser/smt2/Smt2Parser.c:11585
    #3 0x7f068fae093e in term /home/peisen/test/tofuzz/CVC4/build/src/parser/smt2/Smt2Parser.c:10457
    #4 0x7f068fa606f8 in command /home/peisen/test/tofuzz/CVC4/build/src/parser/smt2/Smt2Parser.c:3479
    #5 0x7f068fa49c9d in parseCommand /home/peisen/test/tofuzz/CVC4/build/src/parser/smt2/Smt2Parser.c:2240
    #6 0x7f068f5fe728 in CVC4::parser::Smt2Input::parseCommand() /home/peisen/test/tofuzz/CVC4/src/parser/smt2/smt2_input.cpp:62
    #7 0x7f068f534927 in CVC4::parser::Parser::nextCommand() /home/peisen/test/tofuzz/CVC4/src/parser/parser.cpp:716
    #8 0x426795 in runCvc4(int, char**, CVC4::Options&) /home/peisen/test/tofuzz/CVC4/src/main/driver_unified.cpp:439
    #9 0x439345 in main /home/peisen/test/tofuzz/CVC4/src/main/main.cpp:55
    #10 0x7f065fbe182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 82 byte(s) in 1 object(s) allocated from:
    #0 0x7f0690eb9592 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99592)
    #1 0x7f06752fe15b in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) /usr/include/c++/5/bits/basic_string.tcc:219
    #2 0x7f0673c61533 in CVC4::CommandFailure::CommandFailure(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /home/peisen/test/tofuzz/CVC4/src/./smt/command.h:163
    #3 0x7f0673c3bbed in CVC4::DefineFunctionCommand::invoke(CVC4::SmtEngine*) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:1312
    #4 0x7f0673c3caa0 in CVC4::DefineNamedFunctionCommand::invoke(CVC4::SmtEngine*) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:1357
    #5 0x7f0673c1ebd5 in CVC4::Command::invoke(CVC4::SmtEngine*, std::ostream&) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:174
    #6 0x440111 in CVC4::main::smtEngineInvoke(CVC4::SmtEngine*, CVC4::Command*, std::ostream*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:205
    #7 0x43d3bf in CVC4::main::CommandExecutor::doCommandSingleton(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:121
    #8 0x43c6a1 in CVC4::main::CommandExecutor::doCommand(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:98
    #9 0x4268a1 in runCvc4(int, char**, CVC4::Options&) /home/peisen/test/tofuzz/CVC4/src/main/driver_unified.cpp:446
    #10 0x439345 in main /home/peisen/test/tofuzz/CVC4/src/main/main.cpp:55
    #11 0x7f065fbe182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f0690eb9592 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99592)
    #1 0x7f0673c3bbbd in CVC4::DefineFunctionCommand::invoke(CVC4::SmtEngine*) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:1312
    #2 0x7f0673c3caa0 in CVC4::DefineNamedFunctionCommand::invoke(CVC4::SmtEngine*) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:1357
    #3 0x7f0673c1ebd5 in CVC4::Command::invoke(CVC4::SmtEngine*, std::ostream&) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:174
    #4 0x440111 in CVC4::main::smtEngineInvoke(CVC4::SmtEngine*, CVC4::Command*, std::ostream*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:205
    #5 0x43d3bf in CVC4::main::CommandExecutor::doCommandSingleton(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:121
    #6 0x43c6a1 in CVC4::main::CommandExecutor::doCommand(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:98
    #7 0x4268a1 in runCvc4(int, char**, CVC4::Options&) /home/peisen/test/tofuzz/CVC4/src/main/driver_unified.cpp:446
    #8 0x439345 in main /home/peisen/test/tofuzz/CVC4/src/main/main.cpp:55
    #9 0x7f065fbe182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

~~~~

### PR DESCRIPTION
**Pull request by nafur**
As noted in #4590, CVC4 may leak memory if an exception is thrown that interrupts the command execution loop in `runCvc4()`.
While not a major issue (the binary is terminated anyway in this case, this is also why we label it as feature), we should fix it nevertheless.

This PR makes sure that the current command is properly deleted when `pExecutor->doCommand(cmd)` throws and then rethrows the exception.

### CODE REVIEW

File: src/main/driver_unified.cpp [hunk 1]
```diff
@@ -447,7 +447,16 @@ int runCvc4(int argc, char* argv[], Options& opts) {
...
 
-        status = pExecutor->doCommand(cmd);
+        try
+        {
+          status = pExecutor->doCommand(cmd);
+        }
+        catch (CVC4::Exception& exc)
+        {
+          // Make sure that no memory is leaked an reraise the exception.
+          delete cmd;
```
Comment (4tXJ7f) [inline src/main/driver_unified.cpp:457]: Can we switch to `unique_ptr` for `cmd` instead of adding the `delete` here?

Comment (nafur) [reply src/main/driver_unified.cpp]: Yes, we can! :-) See the new commits.
