### PR TITLE
Fixes for quantifiers + incremental

### LINKED ISSUE #2001: Assertion failure in InstStrategyCbqi::reset_round
The following assertion is triggered on the incremental benchmark BV/20170501-Heizmann-UltimateAutomizer/s3_clnt_3_false-unreach-call_true-no-overflow.BV.c.cil.c.smt2:

```
(error "Assertion failure.
virtual void CVC4::theory::quantifiers::InstStrategyCbqi::reset_round(CVC4::theory::Theory::Effort)
../../../../src/theory/quantifiers/cegqi/inst_strategy_cbqi.cpp:172:

  hasAddedCbqiLemma( q )
")
```

### PR DESCRIPTION
**Pull request by ajreynol**
This distinguishes context-independent "registration" and user-context-dependent "pre-registration" in quantifiers modules. 

Previously, the quantifiers module InstStrategyCbqi (and derived InstStrategyCegqi) were adding lemmas during registration, which is a context-independent method. However, adding lemmas is user-context dependent. Thus, we had potential coherence issues in incremental mode.  This was the cause of #2001. 

This PR changes the name of QuantifiersModule::preRegisterQuantifier to QuantifiersModule::checkOwnership, adds a preRegistration functionality to QuantifiersModules, and updates InstStrategyCbqi/InstStrategyCegqi's registerQuantifier to be preRegisterQuantifier.

This fixes #2001.

Note: the indentation in registerQuantifier changed, although only minor changes were made to this method, namely, reduceQuantifier (which also should be user-context-dependent) was moved to preRegisterQuantifier.

### CODE REVIEW

**Comment by 4tXJ7f** [comment]
I've done a StarExec run on the current set of SMT-LIB benchmarks using a 120s timeout with the competition configuration and have not found any issues.

**Comment by ajreynol** [comment]
You tested the incremental benchmarks? We should probably test non-incremental too.

File: src/theory/quantifiers_engine.cpp [hunk 1]
```diff
@@ -734,54 +735,75 @@ bool QuantifiersEngine::reduceQuantifier( Node q ) {
...
+      Trace("quant-debug") << "check ownership with "
+                           << d_modules[i]->identify() << "..." << std::endl;
+      d_modules[i]->checkOwnership(f);
     }
-  }else{
-    return (*it).second;
+    QuantifiersModule* qm = getOwner(f);
+    if (qm != NULL)
+    {
+      Trace("quant") << "   Owner : " << qm->identify() << std::endl;
```
Comment (HanielB) [inline src/theory/quantifiers_engine.cpp]: Could you change this block to
`` Trace("quant") << "   Owner : " << (qm != NULL? qm->identify() : "none") << std::endl;``
?

File: src/theory/quantifiers_engine.cpp [hunk 2]
```diff
@@ -734,54 +735,75 @@ bool QuantifiersEngine::reduceQuantifier( Node q ) {
...
+    }
+    // register with each module
+    for (unsigned i = 0; i < d_modules.size(); i++)
```
Comment (HanielB) [inline src/theory/quantifiers_engine.cpp]: cache size

File: src/theory/quantifiers_engine.cpp [hunk 3]
```diff
@@ -734,54 +735,75 @@ bool QuantifiersEngine::reduceQuantifier( Node q ) {
...
+    {
+      Trace("quant-debug") << "register with " << d_modules[i]->identify()
+                           << "..." << std::endl;
+      d_modules[i]->registerQuantifier(f);
+      // since this is context-independent, we should not add any lemmas during
+      // this call
+      Assert(d_lemmas_waiting.size() == prev_lemma_waiting);
+    }
+    // TODO: remove this
```
Comment (HanielB) [inline src/theory/quantifiers_engine.cpp]: either remove or mark as in issue

File: src/theory/quantifiers/quant_util.h [hunk 4]
```diff
@@ -113,14 +113,21 @@ class QuantifiersModule {
    * Called once for new quantified formulas that are
    * pre-registered by the quantifiers theory.
    */
-  virtual void preRegisterQuantifier( Node q ) { }
+  virtual void checkOwnership(Node q) {}
```
Comment (HanielB) [inline src/theory/quantifiers/quant_util.h]: update the documentation above this guy (the title)

File: src/theory/quantifiers_engine.cpp [hunk 5]
```diff
@@ -734,54 +735,75 @@ bool QuantifiersEngine::reduceQuantifier( Node q ) {
...
-      Trace("quant-debug")  << "...finish." << std::endl;
-      d_quants[f] = true;
-      // flush lemmas
-      flushLemmas();
-      return true;
+    for (unsigned i = 0; i < d_modules.size(); i++)
+    {
+      Trace("quant-debug") << "check ownership with "
+                           << d_modules[i]->identify() << "..." << std::endl;
+      d_modules[i]->checkOwnership(f);
```
Comment (HanielB) [inline src/theory/quantifiers_engine.cpp]: make sure that this function is not adding lemmas in incremental mode (since e.g. ``InstStrategyCbqi::checkOwnership`` can add lemmas in non-incremental mode)
