### PR TITLE
Fixes for sygus inference on quantifier free problems

### LINKED ISSUE #3199: QF_LRA: assertion failure using --sygus-inference 1
Hello,

For this QF_LRA formula:

```
(set-logic QF_LRA)
(declare-fun v () Real)
(assert (= v 0))
(check-sat)
(get-model)
(exit)
```
CVC4 returns the following assertion failure using the option --sygus-inference:
```
cvc4 --sygus-inference --produce-models test.smt2

(error "Assertion failure.
void CVC4::theory::quantifiers::SynthConjecture::getSynthSolutions(std::map<CVC4::NodeTemplate<true>, CVC4::NodeTemplate<true> >&)
/home/user/software/CVC4/src/theory/quantifiers/sygus/synth_conjecture.cpp:1163:
  fvar.getType() == bsol.getType() ")
```
Omitting that option CVC4 reports that the formula is satisfiable: 
```
cvc4 --produce-models test.smt2
sat
(model
   (define-fun v () Real 0.0)
)
```

OS: Linux 4.15.0-58-generic #64-Ubuntu SMP
Revision: cvc4 1.8-prerelease [git master 16c2fe5e] assertions:on

### LINKED ISSUE #3200: Assertion failure using --sygus-inference 2
Hello, 

For this formula:
```

(set-logic ALL)
(declare-fun v () Real)
(assert (= (* v v) 0))
(check-sat)
(get-model)
(exit)
```

CVC4 returns the following assertion failure using the option --sygus-inference:
```

 cvc4 --sygus-inference t6.smt2 

(error "Assertion failure.

void CVC4::theory::quantifiers::Instantiate::getExplanationForInstLemmas(const std::vector<CVC4::NodeTemplate<true> >&, std::map<CVC4::NodeTemplate<true>, CVC4::NodeTemplate<true> >&, std::map<CVC4::NodeTemplate<true>, std::vector<CVC4::NodeTemplate<true> > >&)

/home/user/software/CVC4/src/theory/quantifiers/instantiate.cpp:672:

  quant.find(lems[j]) != quant.end()

")
```

OS: Linux 4.15.0-58-generic #64-Ubuntu SMP
Revision: cvc4 1.8-prerelease [git master 16c2fe5e] assertions:on

### LINKED ISSUE #3201: Assertion failure using --sygus-inference 3
Hello, 

For this formula:
```
(set-logic ALL)
(declare-fun v () Bool)
(assert false)
(assert v)
(check-sat)
(exit)
```

CVC4 returns the following assertion failure using the option --sygus-inference:

```
 cvc4 --sygus-inference small.smt2

(error "Assertion failure.
CVC4::Node CVC4::theory::quantifiers::CegSingleInv::getSolution(unsigned int, CVC4::TypeNode, int&, bool)
/home/user/software/CVC4/src/theory/quantifiers/sygus/ce_guided_single_inv.cpp:455:
  !d_inst.empty()
")
```

OS: Linux 4.15.0-58-generic #64-Ubuntu SMP
Revision: cvc4 1.8-prerelease [git master 16c2fe5e] assertions:on

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #3199, fixes #3200, fixes #3201. 

We weren't negating the conjecture if it was quantifier-free.  Also a few assertions were too strong.

### CODE REVIEW

File: src/preprocessing/passes/sygus_inference.cpp [hunk 1]
```diff
@@ -261,6 +261,10 @@ bool SygusInference::solveSygus(std::vector<Node>& assertions,
     Node bvl = nm->mkNode(BOUND_VAR_LIST, qvars);
     body = nm->mkNode(EXISTS, bvl, body.negate());
   }
+  else
+  {
+    body = body.negate();
```
Comment (HanielB) [inline src/preprocessing/passes/sygus_inference.cpp]: Instead of this just negate the body before the `if` above.

File: src/theory/quantifiers/sygus/ce_guided_single_inv.cpp [hunk 2]
```diff
@@ -452,17 +452,20 @@ Node CegSingleInv::getSolution(unsigned sol_index,
...
-  Assert(!d_inst.empty());
   const Datatype& dt = ((DatatypeType)(stn).toType()).getDatatype();
   Node varList = Node::fromExpr( dt.getSygusVarList() );
   Node prog = d_quant[0][sol_index];
   std::vector< Node > vars;
   Node s;
-  if( d_prog_to_sol_index.find( prog )==d_prog_to_sol_index.end() ){
+  // If it is unconstrained: either the variable does not appear in the 
+  // conjecture or the conjecture can be solved without a single instantiation.
+  if( d_prog_to_sol_index.find( prog )==d_prog_to_sol_index.end() || d_inst.empty() ){
```
Comment (HanielB) [inline src/theory/quantifiers/sygus/ce_guided_single_inv.cpp]: clang-format
