### PR TITLE
Fix corner case of wrongly applied selector as trigger

### LINKED ISSUE #5766: Fatal failure at src/theory/quantifiers/ematching/candidate_generator.cpp:285
```
[549] % cvc4-1.8 -q small.smt2
unknown
[550] % cvc4 -q small.smt2
Fatal failure within CVC4::theory::inst::CandidateGeneratorSelector::CandidateGeneratorSelector(CVC4::theory::QuantifiersEngine*, CVC4::Node) at src/theory/quantifiers/ematching/candidate_generator.cpp:285
Check failure
 mpatExp.getKind() == APPLY_SELECTOR_TOTAL
Aborted
[551] % 
[551] % cat small.smt2
(declare-datatypes ((a 0))
  (((b (c a) (d a)) (n (o a)) (e (f a) (g a)) (h (i (_ BitVec 1))))))
(declare-fun j (a) Bool)
(declare-fun k (a) a)
(declare-fun l () a)
(assert (forall ((m a)) (=> ((_ is h) m) (j (ite ((_ is b) m) (b m m)
  (ite ((_ is e) m) (e m m) (ite ((_ is b) m) (e m m) (ite (xor ((_
  is n) m) ((_ is e) m)) (b m m) (ite (xor ((_ is n) m) ((_ is n) (o
  m))) (k (o m)) (ite ((_ is n) m) m (ite ((_ is h) m) m
  l)))))))))))
(check-sat)
```
Commit: 8c04f16

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #5766.

### CODE REVIEW

File: src/theory/quantifiers/ematching/candidate_generator.cpp [hunk 1]
```diff
@@ -279,20 +279,32 @@ CandidateGeneratorSelector::CandidateGeneratorSelector(QuantifiersEngine* qe,
...
-  resetForOperator(eqc, d_selOp);
+  // start with d_selOp, if it exists
+  if (!d_selOp.isNull())
+  {
+    resetForOperator(eqc, d_selOp);
+  }
+  else
+  {
+    resetForOperator(d_eqc, d_ufOp);
+  }
```
Comment (HanielB) [inline src/theory/quantifiers/ematching/candidate_generator.cpp:307]:
```suggestion
  resetForOperator(eqc, !d_selOp.isNull()? d_selOp : d_ufOp);
```

**Review by HanielB — APPROVED** [review]
LGTM, just a minor suggestion
