### PR TITLE
Fix length assumption for deq norm emp rule

### LINKED ISSUE #5611: Assertion error at src/theory/uf/equality_engine.cpp:1386
Hi, for the following formula,
cvc4 a3395c1
~~~~
(declare-fun str7 () String)
(declare-fun str8 () String)
(declare-fun str9 () String)
(assert (not (= str8 (str.replace_re_all (str.++ str9 str8 str7) (str.to_re "ULfQhzdcQSfqWSXyjuptqjqsazpyjzdDddlJPLDJhalmhBhlNBKZvoxoLOpfplkqhvIRHMOMDAGIdoRyiZmxmMvRijgpFnd") str9))))
(push)
(assert (and (str.in_re str8 (str.to_re str7)) (not (= str9 (str.replace_re_all (str.++ str8 str8) (str.to_re "ULfQhzdcQSfqWSXyjuptqjqsazpyjzdDddlJPLDJhalmhBhlNBKZvoxoLOpfplkqhvIRHMOMDAGIdoRyiZmxmMvRijgpFnd") str9)))))
(check-sat)
~~~~
~~~~
cvc4 -i -q --strings-exp file.smt2 
Fatal failure within void CVC4::theory::eq::EqualityEngine::getExplanation(CVC4::theory::eq::EqualityNodeId, CVC4::theory::eq::EqualityNodeId, std::vector<CVC4::NodeTemplate<false> >&, std::map<std::pair<unsigned int, unsigned int>, CVC4::theory::eq::EqProof*>&, CVC4::theory::eq::EqProof*) const at /home/CVC4/src/theory/uf/equality_engine.cpp:1386
Check failure

 canExplain

Aborted (core dumped)
~~~~

### PR DESCRIPTION
**Pull request by ajreynol**
There is an assumption that is not guaranteed to hold in this rule, thus we should not try to explain in the equality engine.

Fixes #5611. 

Note this inference was not previously covered in our coverage build.

### CODE REVIEW

File: src/theory/strings/core_solver.cpp [hunk 1]
```diff
@@ -2252,9 +2262,13 @@ bool CoreSolver::processSimpleDeq(std::vector<Node>& nfi,
       Trace("strings-solve-debug")
           << "Disequality normalize empty" << std::endl;
       std::vector<Node> ant;
+      std::vector<Node> antn;
```
Comment (yoni206) [inline src/theory/strings/core_solver.cpp:2265]: Can u document what is `antn` (and also `ant`)?

**Review by yoni206 — APPROVED** [review]
LGTM, one comment inside.
