### PR TITLE
Fix spurious assertion failure in regexp normalization

### LINKED ISSUE #5816: Check failure at src/theory/strings/regexp_solver.cpp:699
```
$ cvc4 bug.smt2 
Fatal failure within CVC4::Node CVC4::theory::strings::RegExpSolver::getNormalSymRegExp(CVC4::Node, std::vector<CVC4::NodeTemplate<true> >&) 
at src/theory/strings/regexp_solver.cpp:699
Check failure
 !utils::isRegExpKind(r.getKind())
Aborted

$ cat bug.smt2
(declare-fun a () String)
(assert (str.in_re a (re.++ (re.* (re.union (re.* (str.to_re "")) (re.union (str.to_re "") (str.to_re a))))
   (re.++ (str.to_re "") (re.++ (re.* (re.range "a" "u")) (str.to_re ""))))))
(check-sat)
```

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #5816.

### CODE REVIEW

File: src/theory/strings/regexp_solver.cpp [hunk 1]
```diff
@@ -664,7 +664,8 @@ Node RegExpSolver::getNormalSymRegExp(Node r, std::vector<Node>& nf_exp)
   switch (r.getKind())
   {
     case REGEXP_EMPTY:
-    case REGEXP_SIGMA: break;
+    case REGEXP_SIGMA: 
+    case REGEXP_RANGE:break;
```
Comment (nafur) [inline src/theory/strings/regexp_solver.cpp:668]: Is this properly formatted?

**Review by nafur — APPROVED** [review]
LGTM.

File: src/theory/strings/regexp_solver.cpp (hunk 1 above)
Comment (ajreynol) [reply src/theory/strings/regexp_solver.cpp]: it wasnt, but i just fixed it.
