### PR TITLE
Fix extended function decomposition

### LINKED ISSUE #2958: Wrong answer for simple string input
```
(set-logic QF_SLIA)
(declare-const x String)
(assert (not (str.prefixof "ab" x)))
(assert (str.in.re (str.substr x 0 2) (re.++ (str.to.re "ab") (re.* (str.to.re "dcab")))))
(check-sat)
```

Current master answers `sat` (model: `(define-fun x () String "A")`) even though this should be `unsat`. `--check-models` fails as expected. This also happens with `--no-re-elim`.

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #2958.

The issue was: we had substr(x,0,2) in R, and the "derivable substitution" modifed this to substr(substr(x,0,2),0,2) in R, since substr(x,0,2) was the representative of x (which is a bad choice, but regardless is legal). Then decomposition inference asked "can i reduce substr(substr(x,0,2),0,2) in R"? It determines substr(substr(x,0,2),0,2) in R rewrites to substr(x,0,2) in R, which is already true. However, substr(x,0,2) in R was what we started with.

The fix makes things much more conservative: we never mark extended functions reduced based on decomposition, since there isnt a strong argument based on an ordering.

### CODE REVIEW

File: src/theory/strings/theory_strings.cpp [hunk 1]
```diff
@@ -1716,23 +1716,15 @@ void TheoryStrings::checkExtfEval( int effort ) {
           Trace("strings-extf-debug") << "  decomposable..." << std::endl;
           Trace("strings-extf") << "  resolve extf : " << sn << " -> " << nrc
                                 << ", const = " << einfo.d_const << std::endl;
-          reduced = sendInternalInference(
+          // We send inferences internal here, which may help show unsat.
+          // However, we do not make a determination whether n can be marked
+          // reduced since this argument may be circular: we may infer than n
+          // can be reduced to something else, but that thing may argue that it
+          // can be reduced to n, in theory).
```
Comment (4tXJ7f) [inline src/theory/strings/theory_strings.cpp]:
```suggestion
          // can be reduced to n, in theory.
```
