### PR TITLE
Fixes for SyGuS PBE + templated string concatenations + datatypes

### LINKED ISSUE #3487: Segfault during SyGuS query
Running CVC4 with --sygus-pbe on this input:
```
(set-logic SLIA)
(declare-datatype JSIdentifier ((JSInt (jsInt Int)) (JSString (jsString String)) (JS_NaN ) ))

(define-fun add2 ((x1_ Int) (x2_ Int)) Int (+ x1_ x2_))
(define-fun add4 ((x1_ String) (x2_ Int)) String (str.++ x1_ (int.to.str x2_)))
(define-fun findArea3 ((x0 String) (x1 Int)) JSIdentifier JS_NaN)

(synth-fun f1 ((x1_ Int)) String
	((Start String (ntString))
		(ntJSIdentifier JSIdentifier
			( 
			(findArea3 ntString ntInt)
			(JSInt ntInt)
			)
		)
		(ntInt Int
			( 0
			(add2 ntInt ntInt)
			(jsInt ntJSIdentifier)
			)
		)
		(ntString String
			(
			(add4 ntString ntInt)
			""
			)
		)
	)
)
(constraint (= (f1 2) "12 8"))
(check-synth)
```
Gives me a segfault:
```
CVC4 suffered a segfault.
Offending address is 0x2c8
Looks like a NULL pointer was dereferenced.
Abort trap: 6
```

Running with --no-sygus-pbe just hangs (as I might expect, I don't expect this to be satisfiable.)

### LINKED ISSUE #3490: Segfault during SyGuS query (2)
Possibly related to #3487.  Wasn't sure whether to edit that issue or create a new one-  I figured this might be better for tracking.

Running this:
```
(set-logic SLIA)
(declare-datatype JSIdentifier ((JSInt (jsInt Int)) (JSString (jsString String)) (JSBool (jsBool Bool)) (JS_NaN )))
(define-fun add1 ((x1_ String) (x2_ String)) String (str.++ x1_ x2_))
(define-fun add3 ((x1_ Int) (x2_ String)) String (str.++ (int.to.str x1_) x2_))
(define-fun add4 ((x1_ String) (x2_ Int)) String (str.++ x1_ (int.to.str x2_)))
(define-fun plusOne2 ((x1_ String)) String (str.++ x1_ (int.to.str 1)))
(define-fun plusTwo2 ((x1_ String)) String (str.++ x1_ (int.to.str 2)))
(define-fun space1 () String " ")
;(define-fun space1 ((x0 Int)) String " ")
(synth-fun results1 ((x1_ Int))String
((Start String (ntString))
(ntString String
( 
(plusTwo2 ntString)
(space1)
;(space1 ntInt)
(plusOne2 ntString)
(add3 ntInt ntString)
(add1 ntString ntString)
(jsString ntJSIdentifier)
(add4 ntString ntInt)

))
(ntInt Int
( x1_
(+ 1 ntInt)
(+ 2 ntInt)
(+ ntInt ntInt)
(jsInt ntJSIdentifier)

))
(ntJSIdentifier JSIdentifier
( 
(JSString ntString)
(JSInt ntInt)
JS_NaN

))
))
(constraint (= (results1 1) "1 2 3"))
(constraint (= (results1 19) "19 20 21"))
(check-synth)
```
Gives an answer in about 5 seconds when using `--no-sygus-pbe`.  But with `--sygus-pbe`, it segfaults:
```
CVC4 suffered a segfault.
Offending address is 0x20000000422
Abort trap: 6
```

(Also, and probably unrelated, if space1- which returns a constant- takes an argument, this takes about 40 seconds with --no-sygus-pbe.  It surprised me that adding an argument to a constant function slowed down SyGuS that much- might be a useful benchmarking case?)

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes two issues when using sygus PBE:
(1) Our string concatenation divide-and-conquer strategy was not robust to the case where the argument type generating a component of a concatenation term was not string (e.g. concatentating terms of the form int.to.str(x)),
(2) Our evaluator was being called on the result of evaluating templated terms, which may involve partial operators such as datatype selectors.

This fixes #3490  and fixes #3487 . Those benchmarks time out now.

### CODE REVIEW

File: src/theory/quantifiers/sygus/sygus_unif_io.cpp [hunk 1]
```diff
@@ -594,12 +594,18 @@ void SygusUnifIo::notifyEnumeration(Node e, Node v, std::vector<Node>& lemmas)
...
       {
         TNode tres = res;
-        std::vector<Node> vals;
-        vals.push_back(tres);
         Node sres;
-        if (tryEval)
+        // It may not be constant, e.g. if we involve a partial operator
+        // like datatype selectors. In this case, we avoid using the evaluator,
+        // which expects a constant substitution.
+        if( tres.isConst() )
```
Comment (HanielB) [inline src/theory/quantifiers/sygus/sygus_unif_io.cpp]: clang-format
